DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
baseURL = ""
description = ""
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
relativeURLs = false
title = "Sporting Chance"
[[menu.main]]
name = "About"
url = "/about"
weight = 20
[[menu.main]]
name = "Services"
url = "/services"
weight = 30
[[menu.main]]
name = "Mentoring"
url = "/mentoring-life-skills"
weight = 1
parent = "Services"
[[menu.main]]
name = "Construction"
url = "/alternative-learning-provision"
weight = 2
parent = "Services"
[[menu.main]]
name = "Testimonials"
url = "/testimonials"
weight = 40
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 50
[params]
description = "The Sporting Chance Project is an Alternative Learning Provider which aims to meet the educational, social and lifestyle needs of young people"
facebook = ""
linkedin = ""
twitter = ""
[security.funcs]
getenv = ["^HUGO_", "^WC_", "CONTEXT", "^URL$", "^DEPLOY_PRIME_URL$"]
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
