DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
baseURL = ""
description = ""
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
relativeURLs = false
title = "Sporting Chance"
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3
[[menu.main]]
name = "Services"
url = "/services"
weight = 2
[[menu.main]]
name = "About Us"
url = "/about"
weight = 1
[params]
description = "The Sporting Chance Project is an Alternative Learning Provider which aims to meet the educational, social and lifestyle needs of young people"
facebook = ""
linkedin = ""
twitter = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
